sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - KAIGA_HEADLESS_TESTS=1

addons:
  apt:
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev
